### ISSUE TITLE
[BUG] ACME Tool not working for DNS challenge with INWX

### ISSUE THREAD

**Issue by franzastisch** [tobychui/zoraxy#922]
**Describe the bug**
When trying to get a certificate with a DNS challenge for DNS provider INWX the following error occurs (XXXXX.XXX is not the domain I used):

Error: one or more domains had a problem: [*.home.XXXXX.XXX] [*.home.XXXXX.XX] acme: error presenting token: inwx: decoding failed due to the following error(s): '[id]' expected type 'int', got unconvertible type 'string' [home.XXXXX.XXX] [home.XXXXX.XXX] acme: error presenting token: inwx: decoding failed due to the following error(s): '[id]' expected type 'int', got unconvertible type 'string'

ACME DNS challenge for same INWX account and same XXXXX.XXX domain works e.g. with homeassistant letsencrypt plugin

**To Reproduce**
1. On Cert Page open ACME Tool
2. In ACME Tool select DNS challenge, DNS Provider INWX and enter required data
3. click Get Certificate
4. after a moment error shows

**Expected behavior**
cert issued

**Host Environment (please complete following information, DO NOT REMOVE ANY FIELD(S)):**
-  Arch: [e.g. arm64] AMD64
 - Device: [e.g. Bananapi R2 PRO] Intel PC
 - OS: [e.g. Armbian] PROXMOX LCX container created by script: https://community-scripts.github.io/ProxmoxVE/scripts?id=zoraxy&category=Network+%26+Firewall
 - Version [e.g.  23.02 Bullseye ]
 - Are you using Docker? (yes / no) no
 - Docker Version (fill in "N/A" for native deployment): [e.g. 3.0.4]

**Comment by tobychui** [comment]
This seems to be another acme compatibility issue to me, what is your Zoraxy version?

**Comment by franzastisch** [comment]
Newest version, v3.3.0
Seems to be a change on INWX side, Traefik had the same issue and fixed it with this https://github.com/traefik/traefik/pull/12333, maybe this helps

**Comment by LucaBeckmann** [comment]
I face exact the same issue.
DNS Provider is also INWX, Zoraxy is baremetal installed and running the newest version 3.3.0.
I know that INWX changed their their API in the last few weeks.

@franzastisch is there any workaround?
My certificates end in a bit over a month and i have no way to renew them.

**Comment by matzepan** [comment]
@LucaBeckmann if you're talking about a couple of certificates, then you can do this by hand as a workaround:

Create the certs using the underlying library:


```shell
mkdir -p certs

docker run --rm \
  -v $(pwd)/certs:/certs \
  -e INWX_USERNAME='user' \
  -e INWX_PASSWORD='password' \
  goacme/lego \
  --email your@mail.com \
  --dns inwx \
  --domains "*.domain.com" \
  --accept-tos \
  --path /certs \
  run
```

And then put them where you need them.

**Comment by LucaBeckmann** [comment]
@matzepan Thank you!
Does this also work with the DNS-Challenge?
Do i just need to insert:
`-e INWX_SHARED_SECRET='xxxx' `

edit:
okay i think i figured it out using the official documentation.

**Comment by matzepan** [comment]
@LucaBeckmann yes this is the DNS-Challenge.
Glad you figured it out.
For everyone else, this is the documentation: https://go-acme.github.io/lego/dns/inwx/index.html

**Comment by osc86** [comment]
What is the current situation?
Does version 3.3.1 contain an updated ACME client?
Using a separate container image just to obtain a certificate is unacceptable.
Another solution would be to transfer all domains away from INWX, preferably to a provider that does not introduce breaking API changes without informing users in advance.

**Comment by tobychui** [comment]
@osc86 You can ping @zen8841 and ask nicely if he got the time to upgrade lego recently. The merge window for 3.3.1-rc1 is closing next week.

**Comment by zen8841** [comment]
I updated Lego, but I don't think this will solve the problem.
I've seen multiple issues with this type-related error, and I have a rough guess as to where it's happened.
However, I need to wait until my university final exams are over before I have time to fix it.

**Comment by franzastisch** [comment]
I was close to dumping Zoraxy and use something else but here's my workaround: I run Zoraxy in a docker container and I installed certbot on the docker host and use it to get the cert and then handed the certs to the Zoraxy container using the naming as described in the wiki: https://github.com/tobychui/zoraxy/wiki/Move-Certificates-to-Zoraxy The only thing misleading in that description was that the cert path is relative to the zoraxy folder not from / so for me it was /opt/zoraxy/conf/certs. So basically the "volume"s section of the docker compose has these two additional entries:
      - /etc/letsencrypt/live/mydomain.tld/cert.pem:/opt/zoraxy/config/conf/certs/mydomain.tld.pem:ro
      - /etc/letsencrypt/live/mydomain.tld/privkey.pem:/opt/zoraxy/config/conf/certs/mydomain.tdl.key:ro
 On the Zoraxy certs page I had to click "refresh list" and it showed up and could be used. Not sure yet if it will just work when it gets updated on the host or if it needs clicking refresh.

**Comment by tobychui** [comment]
> Not sure yet if it will just work when it gets updated on the host or if it needs clicking refresh.

Regarding this, I can provide a bit extra info. This will need to be manually trigger in the current implementation, as Zoraxy do not listen to file change in the certificate folder.

**Comment by osc86** [comment]
I went with the second option and moved all my domains to netcup.
Everything is up and running again, as the netcup plugin works fine using the DNS verification method.

**Comment by isar03** [comment]
I upgraded to 3.3.1 today and re-tried creating a LE wildcard certificate with INWX and DNS challenge, using the built in ACME tool. Tough the ACME tool did "hang" (did not finish), after I hit the Cancel button and refreshed the certs list the certificate was successfully issued.

So principally the upgrade to 3.3.1 fixed this bug, only the ACME tool hang needs to be analyzed and fixed.

**Comment by zen8841** [comment]
Is it similar to the description in #1019 ?

**Comment by isar03** [comment]
@zen8841 - I'm not sure. The first thing that did not work as expected was the ACME tool as the renewing process did not stop from alone. I had to hit "Cancel". 

After that the certificates list did not show the new cert. But "Refresh List" button brought it in the list.

I did some minutes later a restart of the complete VM, so not sure if the certificate really did work before.

LOG: - cert was issued 2026-01-29 10:44:20

[2026-01-29 10:42:52.591881] [ACME] [system:info] CA not set. Using default
[2026-01-29 10:42:52.591976] [ACME] [system:error] Could not extract SANs from PEM, using domainPara only: open ./conf/certs/mydomain.pem: no such file or directory
[2026-01-29 10:42:52.591989] [ACME] [system:info] Obtaining certificate for: *.mydomain, mydomain
[2026-01-29 10:42:52.592000] [ACME] [system:info] Using https://acme-v02.api.letsencrypt.org/directory for CA Directory URL
[2026-01-29 10:44:20.139401] [ACME] [system:info] Restoring HTTP to HTTPS redirect settings
[2026-01-29 10:44:20.139442] [dprouter] [system:info] Restarting proxy server...
[2026-01-29 10:44:20.139510] [dprouter] [system:info] Proxy service stopped successfully
[2026-01-29 10:44:20.139544] [dprouter] [system:info] HTTP to HTTPS redirection listener stopped

[2026-01-29 10:45:20.265074] [uptime-monitor] [system:info] Uptime updated - 1769683520

**Comment by zen8841** [comment]
Can you try the toby's fix?
https://github.com/tobychui/zoraxy/issues/1019#issuecomment-3817197458

**Comment by pleibling** [comment]
Hi, I'm also affected by this issue.

Just wanted to let you know that this has already been fixed upstream in **lego v4.29.0** (released 2025-11-29):

> `[dnsprovider] inwx: fix API breaking changes with record IDs`

See the changelog: https://github.com/go-acme/lego/blob/master/CHANGELOG.md

INWX changed their API to return record IDs as strings instead of integers, which caused the `'[id]' expected type 'int', got unconvertible type 'string'` error. The same issue was also reported in Traefik (traefik/traefik#12338).

So updating the lego dependency in Zoraxy to >= v4.29.0 should resolve this. The latest lego release is v4.31.0.

Thanks @zen8841 for looking into this!

**Comment by zen8841** [comment]
In zoraxy v3.3.1 the lego version is already update to v4.31.0.
Can you check if it fix?

**Comment by pleibling** [comment]
Thanks for your fast Feedback - i check it, now i get not the error at change to dns-challenge and Provider INWX with username and password, but at the changing, it seems to be try to connect, but after an while Zoraxy is not more aviable (have restart the container). The login-information are correct (i can log in with it).

**Comment by PeewX** [comment]
Got the same issue here. It works in general but I have to restart the zoraxy service, then the certificate is shown correctly and seems to work. However, I don't know what happens on renew at some time.

The logs actually looks exactly the same as in the issue mentioned above: #1019

**Comment by pleibling** [comment]
In my case not, how can i see if the process worked and have the wildcard from Lets Encrypt vie DNS Challenge?

**Comment by isar03** [comment]
@pleibling : In my case I had to refresh the list of SSL certs in Zoraxy (3.3.1) and then see the "green" wildcard cert:

<img width="1547" height="185" alt="Image" src="https://github.com/user-attachments/assets/0483a43b-375e-4977-b156-3b09279cb059" />

Then you simply call a DNS registered subdomain of your registered domain and should see it secured with that cert.

**Comment by pleibling** [comment]
Thanks, this can i noch check - cause i want to change to inwx and want to test with Wildcard DNS - all Systems have now leibling.de Adresses and the new one has freie.cloud and Zoraxy can only use 1 Provider, so i think, i have to use an other Zoraxy instance and check - everything is fine, i can change all my DNS to INWX and then change the real certificates. Maybe this is the problem, at this point.

**Comment by PeewX** [comment]
After waiting a few minutes or so, I checked the service (systemctl status zoraxy) noticing that Zoraxy was no longer running. But according to the log, the acme validation was successful, so I started Zoraxy again:

```
[INFO] [*.**.****.de] acme: Waiting for DNS record propagation.
[INFO] [*.**.****.de] The server validated our request
[INFO] [*.**.****.de] acme: Cleaning DNS-01 challenge
[INFO] [*.**.****.de] acme: Validations succeeded; requesting certificates
[INFO] [*.**.****.de] Server responded with a certificate.
[ACME] [system:info] Restoring HTTP to HTTPS redirect settings
[dprouter] [system:info] Restarting proxy server...
[dprouter] [system:info] HTTP to HTTPS redirection listener stopped
[dprouter] [system:error] Error shutting down main server: context deadline exceeded
[dprouter] [system:info] Proxy service stopped successfully
```

**Comment by isar03** [comment]
Peter, I think your (general) questions belong more to the WIKI section.. 
[dprouter] [system:error] Error shutting down main server: context deadline exceeded  >> that one matches the descriptions of others in this thread - ACME renew seems to BREAK zoraxy, already tracked...

**Comment by PeewX** [comment]
> that one matches the descriptions of others in this thread - ACME renew seems to BREAK zoraxy, already tracked...

Absolutely. @tobychui I would say the INWX issue is fixed and can be closed. The main issue seems to be that DNS Wildcard thing that breaks zoraxy sometimes. 



> cause i want to change to inwx and want to test with Wildcard DNS - all Systems have now leibling.de Adresses and the new one has freie.cloud and Zoraxy can only use 1 Provider, so i think, i have to use an other Zoraxy instance and check - everything is fine, i can change all my DNS to INWX and then change the real certificates. Maybe this is the problem, at this point.

@pleibling I am not really sure what you mean. perhaps you should start a thread in the discussions. I use multiple domains in a single Zoraxy intance without any issues so far (beside that new wildard thing of course).

**Comment by zen8841** [comment]
@isar03 @PeewX @pleibling 
This bug has been fix in dev version v3.3.2. https://github.com/tobychui/zoraxy/commit/57fb3ebc49ebea99231802c18a2e8318b4c9396b

**Comment by pleibling** [comment]
@PeewX: I mean that i use 2 Provider at this time - at the first i use Netcup, but there DNSSec is since many month broken and they didn't fix it. There are my domains old domains. So i want to change the Provider (to INWX), cause there DNSSec works well - for testing i get a new domain (freie.cloud) - if DNSSec works and LE Wildcard with DNS Challenge, i want to change my domains to INWX. But there was the same problem with INWX DNS Challenge. I wil check the new one.
